import type { ReactNode } from 'react';
import { Badge } from '@baseflo/ui';
import { IconSparkles } from '@baseflo/ui/icons';

interface ShareShellProps {
  ownerOrgName: string;
  children: ReactNode;
}

/**
 * Layout for the public read-only share page (/s/{token}). Per
 * docs/40-features/WEB-APP.md §5.11 — minimal chrome, polished body.
 */
export function ShareShell({ ownerOrgName, children }: ShareShellProps) {
  return (
    <div className="bg-atmospheric bg-grid-dots flex min-h-full flex-col">
      <header className="border-b border-border bg-surface/80 backdrop-blur-sm">
        <div className="mx-auto flex w-full max-w-3xl items-center justify-between gap-4 px-6 py-4">
          <div className="flex items-center gap-2">
            <span className="text-lg font-semibold tracking-tight text-fg">baseflo</span>
          </div>
          <Badge variant="info" className="flex items-center gap-1.5">
            <span className="relative flex h-1.5 w-1.5">
              <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-info opacity-75" />
              <span className="relative inline-flex h-1.5 w-1.5 rounded-full bg-info" />
            </span>
            Shared workspace · {ownerOrgName}
          </Badge>
        </div>
      </header>
      <main role="main" className="flex-1">
        <div className="mx-auto w-full max-w-3xl px-6 py-12">{children}</div>
      </main>
      <footer className="border-t border-border bg-surface/60 backdrop-blur-sm">
        <div className="mx-auto flex w-full max-w-3xl items-center justify-between px-6 py-4 text-xs text-fg-muted">
          <span className="flex items-center gap-1.5">
            <IconSparkles className="h-3.5 w-3.5 text-accent" />
            Generated by Baseflo's Insight Agent
          </span>
          <a
            href="https://baseflo.com"
            className="text-accent underline-offset-4 hover:underline"
            target="_blank"
            rel="noreferrer"
          >
            Run your business from one place →
          </a>
        </div>
      </footer>
    </div>
  );
}
