"""SQLAlchemy declarative base + shared mixins.

Conventions per docs/04-database-schema.md §2:
- All ids are UUIDv7 (server-generated by default; can be supplied for tests).
- All timestamps are TIMESTAMPTZ, UTC.
- All multi-tenant tables include `organization_id` + RLS policy (added by migration).
- All tables ship with `created_at` + `updated_at`.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any
from uuid import UUID

from sqlalchemy import DateTime, MetaData
from sqlalchemy.orm import DeclarativeBase, Mapped, declared_attr, mapped_column
from sqlalchemy.sql import func

from app.core.ids import new_uuid7

# Constraint naming convention — required for Alembic autogenerate to produce
# stable, replayable migrations. Names are predictable from (table, columns, kind).
NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix__%(table_name)s__%(column_0_N_name)s",
    "uq": "uq__%(table_name)s__%(column_0_N_name)s",
    "ck": "ck__%(table_name)s__%(constraint_name)s",
    "fk": "fk__%(table_name)s__%(column_0_N_name)s__%(referred_table_name)s",
    "pk": "pk__%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base for all ORM models."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)
    type_annotation_map: dict[type, Any] = {}


class TimestampedMixin:
    """Adds created_at + updated_at columns.

    `updated_at` is updated by trigger at the database level (not via SQLAlchemy
    `onupdate`) so writes coming from BYO-DB / direct SQL also keep the column
    current. Trigger is created in the corresponding migration.
    """

    @declared_attr
    @classmethod
    def created_at(cls) -> Mapped[datetime]:
        return mapped_column(
            DateTime(timezone=True),
            nullable=False,
            server_default=func.now(),
        )

    @declared_attr
    @classmethod
    def updated_at(cls) -> Mapped[datetime]:
        return mapped_column(
            DateTime(timezone=True),
            nullable=False,
            server_default=func.now(),
        )


class SoftDeleteMixin:
    """Adds a nullable `deleted_at` column for soft deletes.

    Hard delete is reserved for ephemeral data (sessions, tokens, SSE events).
    """

    @declared_attr
    @classmethod
    def deleted_at(cls) -> Mapped[datetime | None]:
        return mapped_column(DateTime(timezone=True), nullable=True, default=None)


def uuid7_default() -> UUID:
    """Default factory for UUID columns."""
    return new_uuid7()
